CREATE SEQUENCE IF NOT EXISTS routeid START 1;

CREATE TABLE IF NOT EXISTS CITY (
    NAME VARCHAR(255) NOT NULL,
    CODE INT NOT NULL UNIQUE,
    X INT NOT NULL,
    Y INT NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE IF NOT EXISTS ROUTE (
    ID INT NOT NULL DEFAULT nextval('routeid'),
    BEGIN_CITY_CODE INT NOT NULL,
    END_CITY_CODE INT NOT NULL,
    DISTANCE INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BEGIN_CITY_CODE) REFERENCES CITY (CODE),
    FOREIGN KEY (END_CITY_CODE) REFERENCES CITY (CODE)
);